
NAME             = "name"
WIFI_SSID        = "wifi_ssid"
WIFI_PASSWORD    = "wifi_password"
MQTT_BROKER      = "mqtt_broker"
MQTT_PORT        = "mqtt_port"
MQTT_USE_TLS     = "mqtt_use_tls"
TIMEZONE         = "timezone"
BRIGHTNESS       = "brightness"
SLEEP            = "sleep"
WATCHDOG_TIMER   = "watchdog_timer"
CA_DATA          = "ca_data"
MOTION_DETECTION = "motion_detection"
